### ISSUE TITLE
findOrCreate() method return nill

### ISSUE THREAD

**Issue by rockylive** [taka0125/TAKUUID#2]
`var UUID = TAKUUIDStorage.sharedInstance().findOrCreate()`

im using above function to get UUID. it works fine but sometimes its returning nil.

![screen shot 2016-05-25 at 5 13 27 pm](https://cloud.githubusercontent.com/assets/3789511/15538803/121466a4-229c-11e6-8717-fe4fdc3c1bf2.png)

(lldb) po TAKUUIDStorage.sharedInstance().lastErrorStatus
-34018

Any workaround??

**Comment by taka0125** [comment]
Thank you for your feedback.
But, I don't know some workaround.

for your action
http://stackoverflow.com/questions/27752444/ios-keychain-writing-value-results-in-error-code-34018

**Comment by rockylive** [comment]
Can you please do check this will work out. http://stackoverflow.com/a/31421742/2699432
Added the TAKUUIDStorage/Account to keychain groups

**Comment by taka0125** [comment]
Work fine! Thank you.

So, plase try those.

1. Update TAKUUID to 1.4.1
2. Keychain Sharing to ON
3. Set keychain access group and migrate

```swift
TAKUUIDStorage.sharedInstance().accessGroup = "YOUR_KEYCHAIN_ACCESS_GROUP"
TAKUUIDStorage.sharedInstance().migrate()
```
