### ISSUE TITLE
iCoud sharing ?

### ISSUE THREAD

**Issue by terflogag** [taka0125/TAKUUID#3]
Hello,

I'm looking for a good way for generate UUID and store it in the Keychain (only in the current device and not in iCloud). Your library seem to be really nice for doing it ! 
There is no mention about iCloud Keychain sharing, can you confirm me : there are not iCloud Keychain sharing on TAKUUID ? 

Thank you 👍

**Comment by taka0125** [comment]
Thank you for your comment.

I made TAKUUID as an alternative to `advertisingIdentifier`.
So, it does not correspond to iCloud Keychain sharing.

**Comment by terflogag** [comment]
Cool ! Thank you :-)
